
* Attitudinal Scope                                                  :medium:

Attitudinals apply to whatever the scope of the previous word is.

#+BEGIN_SRC 
lo melbi .ui gerku
I'm happy that it's *pretty* (and it happens to be a dog)

lo melbi gerku .ui
I'm happy that it's a dog (and it happens to be pretty)

lo .ui melbi gerku
I'm happy that it's a *pretty dog*
#+END_SRC

Look at the previous word, and see what it applies to. In the last
example, ~lo~ applies to all of ~melbi gerku~, so the ~ui~ applies to all of
~melbi gerku~ too.

Knowing this, you can understand this phrase:

#+BEGIN_SRC 
re verba cu .ui kelci 
I'm happy that two children are playing.
#+END_SRC

I'm not happy due to the ~cu~, I'm happy due to whatever the ~cu~
covers. In this case, that's the ~kelci~.

* Shared arguments in predicates                                     :medium:

gi'e joins relationships, but only shares the arguments before the
first relation, or after vau.

#+BEGIN_SRC 
mi citka gi'e pinxe
= mi citka zo'e gi'e pinxe zo'e

I eat and drink (different things)
#+END_SRC

#+BEGIN_SRC 
mi dunda su'o plise gi'e cpacu su'o perli vau do
= mi fi do dunda fe su'o plise gi'e cpacu fe su'o perli
= dunda su'o plise gi'e cpacu su'o perli vau fa mi fi do

I [give an apple (to)] and [get a pear (from)] you
#+END_SRC

By contrast, je shares all arguments.

#+BEGIN_SRC 
mi citka je pinxe
= mi citke je pinxe zo'e

I eat and drink (the same thing)
#+END_SRC

* Grouping in compound tanru                                         :medium:

Normally, tanru are left-grouping:

#+BEGIN_SRC 
melbi nixli ckule
(pretty girls)' school
#+END_SRC

You can use ~bo~ to do right-grouping:

#+BEGIN_SRC 
melbi nixli ckule
pretty (girls' school)
#+END_SRC

Lojban has an equivalent to (), which is ~ke~ and ~ke'e~:

#+BEGIN_SRC 
melbi ke nixli ckule ke'e
pretty (girls' school)
#+END_SRC

~ke~ is simpler, but requires you to use it in advance. The nice thing
about ~bo~ is that you can use it when you realise later that you have
more to say.
